#!/usr/bin/python

sources =  [
            'nodedemog_module.cpp',
            '../../utils/Configure.cpp',
            '../../utils/EventTrigger.cpp',
            '../../utils/Exceptions.cpp',
            '../../Eradication/ConfigParams.cpp',
            '../../Eradication/BroadcasterImpl.cpp',
            '../../Eradication/Node.cpp',
            '../../Eradication/NodeDemographics.cpp',
            '../../Eradication/NodeEventContext.cpp',
            '../../Eradication/Individual.cpp',
            '../../Eradication/Susceptibility.cpp',
            '../../Eradication/Infection.cpp',
            '../../Eradication/InterventionsContainer.cpp',
            '../../Eradication/SerializationParameters.cpp',
            '../../Eradication/StrainIdentity.cpp',
            '../../Eradication/SimulationEnums.cpp',
            '../../Eradication/TBHIVDrugTypeParameters.cpp',
            '../../Eradication/TBDrugTypeParameters.cpp',
            '../../Eradication/Instrumentation.cpp',
            '../../Eradication/TransmissionGroupsBase.cpp',
            '../../Eradication/StrainAwareTransmissionGroups.cpp',
            '../../Eradication/TransmissionGroupsFactory.cpp',
           ]
