# -*- mode: python; -*-
# This Python script, SConscript, invoked by the SConscript in the upper directory,
#
# 1. builds sqlite static library

Import("env")

sqliteSrcFiles = ["sqlite3.c",
                  "stdafx.cpp"
                 ]

sqliteIncFiles = [ 'sqlite3.h']
sqliteLocalInc = ['stdafx.h']

sqliteLib = env.StaticLibrary('libsqlite', sqliteSrcFiles)
